### ISSUE TITLE
A reminder email is not being sent.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/woocommerce-abandoned-cart#735] opened 2021-06-11 11:58 UTC
**Describe the bug**
A reminder email is not being sent.

**To Reproduce**
1. Abandon the cart on the site https://testcampioni.bioluma.it/
2. Your abandoned cart will be listed on the Abandoned Orders tab but the reminder email is not sending to clients.

Enable abandoned cart emails setting is enabled.
Email template is enabled and it is set to 1 hour. 
Test email is receiving from the client's site.

Note: This issue is only replicating on the client's site, not on our staging site.

The client's access is added to the ticket.

**Expected behavior**
A reminder email should be sent for abandoned carts.

**Screenshots or Video**

**Isolating the problem (mark completed items with an [x]):**
 [x] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [ ] This bug happens with a default WordPress theme active, or [Storefront]
 [ ] I can reproduce this bug consistently using the steps above

https://tychesoftwares.freshdesk.com/a/tickets/29666

**Comment by pinalj** [comment] 2021-07-19 12:58
WP Cron was disabled on the client site. We requested them to enable it as the action scheduler relies on WP cron to run the actions. The issue is not replicated at our end with WP Cron enabled. Hence closing.

**Closed by pinalj** 2021-07-19 12:58 UTC
Labels: Client Issue, type : bug
