### ISSUE TITLE
The 'From' e-mail address is showing incorrectly in the reminder email.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/woocommerce-abandoned-cart#863] opened 2023-03-06 10:01 UTC
**Describe the bug**
The 'From' e-mail address is showing incorrectly in the reminder email.

**To Reproduce**
1. Email Sending Settings on a client site are set to: https://www.screencast.com/t/X7kXAqarrcJZ
2. Abandon a cart on his site. You will receive a reminder email from his site where you can see the 'From' e-mail address is showing incorrectly.

**Note: I am unable to replicate this issue on my local site. I am able to replicate it only on a client site. Client's access details are added in the ticket sidebar.**

**Expected behavior**
The 'From' e-mail address should show correctly in the reminder email.

**Screenshots or Video**
https://www.screencast.com/t/X7kXAqarrcJZ
https://www.screencast.com/t/x0TeFFe6QFEw

**Isolating the problem (mark completed items with an [x]):**
 [x] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [x] This bug happens with a default WordPress theme active, or [Storefront]
 [ ] I can reproduce this bug consistently using the steps above

**Additional context**
https://tychesoftwares.freshdesk.com/a/tickets/52014

**Comment by pinalj** [comment] 2023-03-08 09:25
1. We have checked and confirmed that the email headers (i.e. from name and email) are added correctly by our plugin when the reminder email is sent.
2. We noticed that when we sent some test emails from the site, the from name and email is set as No Reply - Pethical <noreply@pethical.co.uk>
2. Maybe there are some settings in place on the site/server which is forcing the From Name and email address. That seems to be the most likely conclusion here.

The client has confirmed "There was a setting which was incorrectly set … your plug-in must have picked that up … nothing else seemed to."

No fixes are needed in our plugin code. Hence closing.

**Closed by pinalj** 2023-03-08 09:25 UTC
Labels: type: bug, type: not replicated, severity: minor, client issue
